spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration

  application:
    name: things

  datasource:
    username: things
    password: things
    url: jdbc:postgresql://postgres:5432/things
    driver-class-name: org.postgresql.Driver

axon:
  config:
    packages:
      - com.things.one
  axonserver:
    servers: axonserver
    context: things

    management:
      server:
        port: 9029
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true

